# author: Herbert Koelman
# created on: Jeu 21 nov 2019 14:44:25 CET
os: linux
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install -r requirements.txt

env:
  CODECOV_TOKEN="6fa05a9c-1a01-4123-b726-d493275017cd"

# Travis CI uses shallow clone to speed up build times, but a truncated SCM history may cause issues
# when SonarCloud computes blame data.
git:
  depth: false

# Run travis on these branches only...
branches:
  only:
    - master
    - develop

addons:
  sonarcloud:
    organization: "herbertkoelman-github"

script:
  - python ./setup.py test && python ./setup.py sdist

#after_success:
#  - do something (upload ?)